worker_processes 1;

error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        location = /kevin_gonzalez {
            return 301 /kevin_gonzalez/;
        }

        location = /kevin_gonzalez/viejapagina {
            return 301 /kevin_gonzalez/nuevapagina;
        }

        location ~* ^/kevin_gonzalez/.*\.(env|git|bak)$ {
            deny all;
        }

        location = /kevin_gonzalez/404.html {
            alias "C:/Users/kevin/Documents/Desarrollo web Profesional/Parcial 1/Practica TIENDA COSMETICOS/deploy/local/www/kevin_gonzalez/404.html";
            internal;
        }

        location ^~ /kevin_gonzalez/admin {
            allow 127.0.0.1;
            allow ::1;
            allow 2806:290:a800:8fe5:e54d:7249:f31d:227a;
            allow IP_DE_RESPALDO_AQUÍ;
            deny all;

            alias "C:/Users/kevin/Documents/Desarrollo web Profesional/Parcial 1/Practica TIENDA COSMETICOS/deploy/local/www/kevin_gonzalez/";
            error_page 404 /kevin_gonzalez/404.html;
            try_files $uri =404;
        }

        location = /kevin_gonzalez/ {
            alias "C:/Users/kevin/Documents/Desarrollo web Profesional/Parcial 1/Practica TIENDA COSMETICOS/deploy/local/www/kevin_gonzalez/index.html";
        }

        location = /kevin_gonzalez/index.html {
            alias "C:/Users/kevin/Documents/Desarrollo web Profesional/Parcial 1/Practica TIENDA COSMETICOS/deploy/local/www/kevin_gonzalez/index.html";
        }

        location /kevin_gonzalez/ {
            alias "C:/Users/kevin/Documents/Desarrollo web Profesional/Parcial 1/Practica TIENDA COSMETICOS/deploy/local/www/kevin_gonzalez/";
            error_page 404 /kevin_gonzalez/404.html;
            try_files $uri =404;
        }
    }
}
