location /kevin_gonzalez/api/ {
    rewrite ^/kevin_gonzalez/api/(.*) /$1 break;
    proxy_pass http://localhost:3006;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /kevin_gonzalez/panel/ {
    allow 10.0.0.0/8;
    allow 201.143.107.182;
    allow 2806:290:a800:8fe5:8997:6761:2637:e3f1;
    deny all;
    alias /home/kevin_gonzalez/public/panel/;
    try_files $uri $uri/ =404;
}

location ~* /kevin_gonzalez/.*\.(env|git|bak)$ {
    deny all;
    return 404;
}

location = /kevin_gonzalez/vieja {
    return 301 /kevin_gonzalez/nueva;
}

location = /kevin_gonzalez/404.html {
    alias /home/kevin_gonzalez/public/404.html;
    internal;
}

location = /kevin_gonzalez/ {
    alias /home/kevin_gonzalez/public/index.html;
}

location /kevin_gonzalez/ {
    alias /home/kevin_gonzalez/public/;
    index index.html;
    error_page 404 /kevin_gonzalez/404.html;
    try_files $uri $uri/ =404;
}
